Added CodeCoverage support

diff --git a/.github/workflows/run-unit-test-and-upload-codecov.yml b/.github/workflows/run-unit-test-and-upload-codecov.yml
--- a/.github/workflows/run-unit-test-and-upload-codecov.yml
+++ b/.github/workflows/run-unit-test-and-upload-codecov.yml
@@ -15,7 +15,7 @@
 name: Run Unit Test and Upload Coverage Report
 
 on:
-  # Triggered whenever push to main
+  # Triggered whenever push to main 
   push:
     branches: [ "main" ]
 
@@ -32,34 +32,38 @@ jobs:
     # Create a container of the latest Ubuntu, other values could be
     # ubuntu-latest, ubuntu-22.04, etc.
     runs-on: ubuntu-22.04
-
+    
     steps:
       # We want to use GitHub CI checkout version 3 to check out our branch
       - uses: actions/checkout@v3
-
+      
       # Install some system pacakges
       - name: Install build packages
         run: |
           sudo apt update
           sudo apt install -y software-properties-common
           sudo apt install -y doxygen lcov gcovr
-          sudo apt-get install -y libeigen3-dev       // Installing Eigen3 in the build environment
-
-
+          
       # Build, run unit test, and generate coverage report
       - name: Configure CMake flags and build exectables
         run: |
           cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S ./ -B build/
           cmake --build build/ --clean-first --target all test_coverage
-          cat build/test_coverage.info
 
+      # Ensure the coverage file exists
+      - name: Check for coverage report
+        run: |
+          if [ ! -f build/test_coverage.info ]; then
+            echo "Coverage report not found!"
+            exit 1
+          fi
+          
       # Upload coverage result to CodeCov
       - name: Upload coverage result to CodeCov
-        uses: codecov/codecov-action@v4
+        uses: codecov/codecov-action@v3
         with:
-          token: ${{ secrets.CODECOV_TOKEN }} # required (must add token in your github repo)
+          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
           files: ${{github.workspace}}/build/test_coverage.info
           fail_ci_if_error: true # optional (default = false)
-          verbose: true # optional (default = false)
-          disable_search: true # optional (default = false)
-          plugin: none         # optional (xcode, gcov, pycoverage)
+          verbose: true # optional (default = false)      
+          
